### ISSUE TITLE
Clang compiler support

### ISSUE THREAD

**Issue by IvanFilipov** [IvanFilipov/SDP---students#27]
Currently [kruztev](https://github.com/kruztev) is maintaining the clang support for our examples, if you have any questions, go ahead - ask him here :)

**Comment by kruztev** [comment]
Checked up to commit 599d9fe4ac1e5345186e96faf143e0da16143d9e inclusively.
Currently testing the hash_table example.

**Comment by kruztev** [comment]
Checked up to commit 57257ebc2edfe4d268827afedee83af4f81e8691 inclusively.

**Comment by IvanFilipov** [comment]
After 00a9c7d32633e43f68dfdefbc0fb442979078802 everything should be fine. Closing.
