### ISSUE TITLE
A warning for operator<<

### ISSUE THREAD

**Issue by kruztev** [IvanFilipov/SDP---students#29]
https://github.com/IvanFilipov/FMI-DSA/blob/53a27422e88a21e50de7fb8f8ec032f4b356c7ed/data_structures/tree/binary_search_tree/template_bst/bs_tree.hpp#L249
"Call to function 'operator<<' that is neither visible in the template definition nor found by argument-dependent lookup".

**Comment by IvanFilipov** [comment]
Fixed in fa5f1c4fa0e2f7ea406b2cb4fc2e67d87ab555c4.
