### ISSUE TITLE
Bucket sort which uses constant memory

### ISSUE THREAD

**Issue by NoHomey** [IvanFilipov/SDP---students#3]
The idea is to use linked list (single) to remove the need of queues which are normally used as buckets which ensures the stability of the algorithm. There is no need of queues since the list's node can be freely moved around which is impossible with continuous linear memory structures such as dynamic arrays (vectors).

Here is a basic [implementation wich sorts in ascending order](https://github.com/NoHomey/bucket-sort-with-const-memory/blob/8ab8e279fa3e7356127f723eaa5a9f7bdd63ad1b/src/SingleLinkedList/SingleLinkedList.tci#L113-L132).

**Comment by IvanFilipov** [comment]
Изглежда ми ОК.
