### ISSUE TITLE
Dynamic_array potential logic error in insert_at

### ISSUE THREAD

**Issue by mom4ilakis** [IvanFilipov/SDP---students#35]
https://github.com/IvanFilipov/FMI-DSA/blob/300bf89bf6696007b0c9bb458f5dd8e166d4a928/data_structures/dynamic_array/dynamic_array.hpp#L400

shouldn't it  be size_t index = it - iterator(data), so we use the defined operator-() in class iterator ?

**Comment by IvanFilipov** [comment]
In this case `data_ptr` is automaticallty cast to iterator type, so `iterator::operator-()` is called.

**Comment by IvanFilipov** [comment]
Closing (not error at all)
