### ISSUE TITLE
VC++ compiler support

### ISSUE THREAD

**Issue by IvanFilipov** [IvanFilipov/SDP---students#6]
**all** examples should be tested with VC++ also

**Comment by IvanFilipov** [comment]
checked up to commit 76a96a6466d37132f533bbbcae4e7847641a63b7 inclusively.

**Comment by VasiPeycheva** [comment]
checked up to commit  47eac3ade0834247eb5674cd756dd4911db11b0f inclusively.

**Comment by VasiPeycheva** [comment]
checked up to commit 208767f7ee933e48ccdf7d0e04cab2cd6d7f2ce6 inclusively.

**Comment by VasiPeycheva** [comment]
checked up to commit d6e2c78f18d2f10f433721d91a0aba29dbe69ff9 inclusively.

**Comment by VasiPeycheva** [comment]
checked up to commit 8c1db28072c07e9efbd81bd5b4cf69f52e23a813 inclusively.

**Comment by VasiPeycheva** [comment]
checked up to commit 00a9c7d32633e43f68dfdefbc0fb442979078802 inclusively.
